version: '3.8'

services:
  db:
    build:
      dockerfile: Dockerfile
      context: ./db
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
    volumes:
      - ./db/data:/data

  web:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "3000:$APP_PORT"

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    depends_on:
      - db
    environment:
      - DB_PASS
      - DB_IP=db

  admin:
    image: adminer
    restart: always
    ports:
      - 8080:$ADMIN_PORT