version: '3.0'
services:
  play:
    build: .
    ports:
    - "8080:80"
    - "5432:5432"
    volumes:
    - ./api/src:/vagrant/api/src
    - ./app/src:/vagrant/app/src
    - ./app/public:/vagrant/app/public
    - ./db/datafiles:/vagrant/db/datafiles
    - ./web/www:/vagrant/web/www
    - ./web/default:/vagrant/web/default
    stdin_open: true
    tty: true
    user: vagrant
    command: bash -c "
      sudo service nginx restart
      && sudo service postgresql restart
      && . ~/dbpass.sh
      && PORT=3001 pm2 start -n api node -- api/src/server.js
      && cd app
      && PORT=3000 pm2 start -n react npm -- start
      && echo 'Playpen Started'
      && bash"